//
// Created by Julius on 26.09.2025.
//

#ifndef CUSTOMIZABLECONTRACTIONHIERARCHY_ELIMINATIONTREEQUERY_HPP
#define CUSTOMIZABLECONTRACTIONHIERARCHY_ELIMINATIONTREEQUERY_HPP

#endif //CUSTOMIZABLECONTRACTIONHIERARCHY_ELIMINATIONTREEQUERY_HPP
