//
// Created by Julius on 26.09.2025.
//

#ifndef CUSTOMIZABLECONTRACTIONHIERARCHY_BASICCUSTOMIZER_HPP
#define CUSTOMIZABLECONTRACTIONHIERARCHY_BASICCUSTOMIZER_HPP

#endif //CUSTOMIZABLECONTRACTIONHIERARCHY_BASICCUSTOMIZER_HPP
